CREATE TYPE claim_state AS ENUM ('CAPTURING','TRANSCRIBING','CLAIM_CANDIDATE','CHECKING','EVIDENCE_READY','SYNTHESIZING','COMPLETE','INSUFFICIENT_EVIDENCE','FAILED');
CREATE TABLE sessions (id uuid PRIMARY KEY, idempotency_key text UNIQUE NOT NULL, video_url text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE claims (id uuid PRIMARY KEY, public_id text UNIQUE NOT NULL, session_id uuid NOT NULL REFERENCES sessions(id), idempotency_key text NOT NULL, speaker_label text NOT NULL, exact_text text NOT NULL, normalized_text text NOT NULL, normalized_claim_hash text NOT NULL, start_ms integer CHECK(start_ms>=0), end_ms integer CHECK(end_ms>=start_ms), classification text NOT NULL CHECK(classification IN ('opinion','factual_claim','unverifiable')), state claim_state NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz, body jsonb NOT NULL, UNIQUE(session_id,idempotency_key));
CREATE INDEX claims_public_idx ON claims(public_id); CREATE INDEX claims_state_idx ON claims(state); CREATE INDEX claims_hash_idx ON claims(normalized_claim_hash);
CREATE TABLE evidence (id text PRIMARY KEY, claim_id uuid NOT NULL REFERENCES claims(id), stance text NOT NULL, title text NOT NULL, canonical_url text NOT NULL, publisher text NOT NULL, published_at timestamptz, retrieved_at timestamptz NOT NULL, excerpt text NOT NULL, source_tier text NOT NULL, content_hash text NOT NULL, UNIQUE(claim_id,canonical_url));
CREATE TABLE verdicts (claim_id uuid PRIMARY KEY REFERENCES claims(id), label text NOT NULL, confidence numeric CHECK(confidence BETWEEN 0 AND 1), explanation text NOT NULL, uncertainty text NOT NULL, counterevidence_summary text NOT NULL, common_ground text, citation_ids text[] NOT NULL, model_provider text NOT NULL, model_name text NOT NULL, prompt_version text NOT NULL);
CREATE TABLE push_subscriptions (id uuid PRIMARY KEY, device_id text UNIQUE NOT NULL, endpoint text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE notification_outcomes (claim_id uuid REFERENCES claims(id), subscription_id uuid REFERENCES push_subscriptions(id), status text NOT NULL, PRIMARY KEY(claim_id,subscription_id));
CREATE TABLE usage_ledger (id uuid PRIMARY KEY, session_id uuid REFERENCES sessions(id), units numeric NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
